<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{0fd8f3bb-2875-4327-87a4-a5acbddc9687}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GameEngine();

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="55" Count="0" />
      <LineId Id="60" Count="0" />
      <LineId Id="59" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>